monitors:
  # HTTP service monitoring
  - name: "HTTP Service"
    type: "http"
    interval: "30s"
    timeout: "5s"
    http:
      url: "http://helloworld-http:8080/ping"
      method: "GET"
      headers:
        Authorization: "Bearer secret-token"
        Content-Type: "application/json"

  # Postgres monitoring
  - name: "PostgreSQL Service"
    type: "database"
    interval: "30s"
    timeout: "10s"
    database:
      driver: "postgres"
      connection_string: "postgres://postgres:postgres@postgres-db:5432/monitoring?sslmode=disable"
      query: "SELECT 1"

  # MySQL monitoring
  - name: "MySQL Service"
    type: "database"
    interval: "30s"
    timeout: "10s"
    database:
      driver: "mysql"
      connection_string: "root:mysql@tcp(mysql-db:3306)/monitoring"
      query: "SELECT 1"

  # MariaDB monitoring
  - name: "MariaDB Service"
    type: "database"
    interval: "30s"
    timeout: "10s"
    database:
      driver: "mariadb"
      connection_string: "root:mariadb@tcp(mariadb-db:3306)/monitoring"
      query: "SELECT 1"

  # Redis monitoring (primary)
  - name: "Redis Service Primary"
    type: "database"
    interval: "5s"
    timeout: "5s"
    database:
      driver: "redis"
      database: 0
      host: "redis-db"
      port: 6379
      password: "redispassword"

  # MSSQL monitoring
  - name: "MSSQL Service" 
    type: "database"
    interval: "30s"
    timeout: "10s"
    database:
      driver: "mssql"
      host: "mssql-db"
      port: 1433
      username: "SA"
      password: "Password1!"
      database: "master"
      query: "SELECT 1"

