monitors:
  # HTTP service monitoring
  - name: "Company Website"
    type: "http"
    interval: "30s"
    timeout: "5s"
    http:
      url: "http://athena-http-test/health"
      method: "GET"
      headers:
        Authorization: "Bearer secret-token"
        Content-Type: "application/json"

  # Database with structured parameters
  - name: "Main Database"
    type: "database"
    interval: "1m"
    timeout: "10s"
    database:
      driver: "mysql"
      host: "db.company.com"
      port: 3306
      username: "health_checker"
      password: "secret123"
      database: "production"
      query: "SELECT 1"

  # Database with connection string
  - name: "Analytics Database"
    type: "database"
    interval: "5m"
    timeout: "15s"
    database:
      driver: "mysql"
      connection_string: "mysql://monitor:monitor123@analytics-db.company.com:3306/analytics"
      query: "SELECT COUNT(*) FROM events WHERE created_at >= NOW() - INTERVAL 1 HOUR"

  # PostgreSQL with connection string
  - name: "User Database"
    type: "database"
    interval: "2m"
    timeout: "10s"
    database:
      driver: "postgres"
      connection_string: "postgresql://app_user:pass123@users-db.company.com:5432/users?sslmode=verify-full"
      query: "SELECT 1"
