monitors:
  # HTTP service monitoring (external)
  - name: "HTTP Service External"
    type: "http"
    interval: "5s"
    timeout: "5s"
    http:
      url: "http://localhost:8081/ping"
      method: "GET"
      headers:
        Authorization: "Bearer secret-token"
        Content-Type: "application/json"

  # Postgres monitoring (external)
  - name: "PostgreSQL Service External"
    type: "database"
    interval: "5s"
    timeout: "10s"
    database:
      driver: "postres"
      connection_string: "postgres://postgres:postgres@localhost:6543/monitoring?sslmode=disable"
      query: "SELECT 1"

  # MySQL monitoring (external)
  - name: "MySQL Service External"
    type: "database"
    interval: "5s"
    timeout: "10s"
    database:
      driver: "mysql"
      connection_string: "root:mysql@tcp(localhost:3306)/monitoring"
      query: "SELECT 1"

  # MariaDB monitoring (external)
  - name: "MariaDB Service External"
    type: "database"
    interval: "5s"
    timeout: "10s"
    database:
      driver: "mariadb"
      connection_string: "root:mariadb@tcp(localhost:3307)/monitoring"
      query: "SELECT 1"

  - name: "Redis Service External"
    type: "database"
    interval: "5s"
    timeout: "5s"
    database:
      driver: "redis"
      # connection_string: "redis://redisuser:redispassword@localhost:6379/1"
      database: "1"
      host: "localhost"
      port: 6379
      password: "redispassword"
      username: "redisuser"
      query: "PING"

  - name: "MSSQL Service External" 
    type: "database"
    interval: "5s"
    timeout: "10s"
    database:
      driver: "mssql"
      host: "localhost"
      port: 1433
      username: "SA"
      password: "Password1!"
      database: "master"
      query: "SELECT 1"

