services:
  pulsebridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsebridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - PULSE_BRIDGE_CONFIG=/app/config.yml
    volumes:
      - ./config.yml:/app/config.yml:ro
    networks:
      - pulsebridge-network

  pulsebridge-http-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsebridge-http-test
    ports:
      - "8081:8080"
    environment:
      - GO_ENV=production
      - PULSE_BRIDGE_CONFIG=/app/config.yml
    volumes:
      - ./config.yml:/app/config.yml:ro
    networks:
      - pulsebridge-network

networks:
  pulsebridge-network:
    driver: bridge
