services:
  pulsebridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulsebridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - PULSE_BRIDGE_CONFIG=/app/config.yml
    volumes:
      - ./config.yml:/app/config.yml:ro
    networks:
      - pulsebridge-network

  helloworld-http:
    image: testcontainers/helloworld:latest
    container_name: helloworld-http
    ports:
      - "8081:8080"
    networks:
      - pulsebridge-network
  
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitoring
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pulsebridge-network

  redis-db:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass redispassword
      --databases 2
    volumes:
      - redis-data:/data
    networks:
      - pulsebridge-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=monitoring
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pulsebridge-network

  mariadb-db:
    image: mariadb:latest
    container_name: mariadb-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=monitoring
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - pulsebridge-network

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - pulsebridge-network

networks:
  pulsebridge-network:
    driver: bridge

volumes:
  postgres-data:
  mysql-data:
  mariadb-data:
  mssql-data:
  redis-data:
