replicaCount: 1
image:
  repository: ghcr.io/wavezync/pulse-bridge
  pullPolicy: IfNotPresent
  tag: ""
service:
  type: ClusterIP
  port: 8080
livenessProbe:
  httpGet:
    path: /health
    port: 8080
readinessProbe:
  httpGet:
    path: /health
    port: 8080
env:
  - name: PULSE_BRIDGE_CONFIG
    value: "/etc/pulsebridge/helm-config.yml"
configContent:
  monitors:
    # HTTP service monitoring
    - name: "HTTP Service"
      type: "http"
      interval: "30s"
      timeout: "5s"
      http:
        url: "http://helloworld-http:8080/ping"
        method: "GET"
        headers:
          Authorization: "Bearer secret-token"
          Content-Type: "application/json"

    # Postgres monitoring
    - name: "PostgreSQL Service"
      type: "database"
      interval: "30s"
      timeout: "10s"
      database:
        driver: "postgres"
        connection_string: "postgres://postgres:postgres@postgres-db:5432/monitoring?sslmode=disable"
        query: "SELECT 1"