name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main","*" ]

jobs:

  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  trigger-binaries:
    needs: build-go
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/binaries.yml
    secrets: inherit

  trigger-docker-build:
    needs: build-go
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/docker.yml
    secrets: inherit
