apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulse-bridge.name" . }}
  labels:
    {{- include "pulse-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulse-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pulse-bridge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "pulse-bridge.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PULSE_BRIDGE_CONFIG
              value: "/config/config.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "pulse-bridge.name" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}